### ISSUE TITLE
Connect to the backend

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/financeular#26]
* [x] Maintain access token - #29
* [x] Check if the user is logged in or not - #30
* [x] Update default budget - #31
* [x] Save default income - #32 
* [x] Register a new user - #34
